-- Phase 27: AI-Driven Anatomy Analysis
-- Adding AI intelligence layers to clinical requests

ALTER TABLE appointment_requests 
ADD COLUMN IF NOT EXISTS ai_analysis JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS ai_conclusion TEXT,
ADD COLUMN IF NOT EXISTS ai_humanoid_markers JSONB DEFAULT '[]'::jsonb;

-- Comment for clarity
COMMENT ON COLUMN appointment_requests.ai_analysis IS 'Full raw JSON response from Gemini analysis';
COMMENT ON COLUMN appointment_requests.ai_conclusion IS 'Concise clinical summary generated by AI';
COMMENT ON COLUMN appointment_requests.ai_humanoid_markers IS 'List of anatomical parts with status (RED, ORANGE, GREEN) for 3D visualization';
